name: Release

on:
  push:
    tags:
      - "v*"

jobs:

  Release:
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
      # For generating GitHub Releases + Release notes
      # ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - run: |
          pip install uv
          uv pip install --system build
          python -m build

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npx changelogithub@0.12
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
